sudo: required

services: docker

before_install:
  - docker-compose up -d --build

script:
  - docker-compose exec --env 'RAILS_ENV=production' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=production' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=production' web bin/rspec
