version: '3'

services:
  db:
    image: postgres@sha256:781d600ca4225da054712b4bb1db3c44a86c28a6d19c5fcff314ce78c1225860
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    links:
      - db
      - chrome
    tty: true
    stdin_open: true
    environment:
      - 'DATABASE_PASSWORD=postgres'
      - 'SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub'

  chrome:
    image: selenium/standalone-chrome@sha256:4a590fc95d67a8eb13464799583991daa6a8548c9a9e2e7f234a92c9c4fa8f29   #Chromeがインストールされたイメージ
    ports:
      - "4444:4444"

  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"