default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: myapp_test_development

test:
  <<: *default
  host: localhost
  database: myapp_test

# production:
#   url: <%= ENV['DATABASE_URL']%>

production:
  <<: *default
  database: <%= ENV['MYAPP_DATABASE'] %>
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>
