default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD")   %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsapp_test_development

test:
  <<: *default
  database: railsapp_test_test

# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: railsapp_test_production