default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_test_development

test:
  <<: *default
  database: myapp_test

production:
  url: <%= ENV['DATABASE_URL']%>

# production:
#   <<: *default
  # database: myapp_production
  # username: postgres
  # password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
