default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_test_development

test:
  <<: *default
  database: myapp_test_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['DATABASE_PASSWORD'] %>
